require('plugins')
require('keymaps')
require('settings')
require('nvim-tree-config')
require('lualine-config')
require('bufferline-config')
require('whichkey-config')
require('treesitter-config')
require('autopairs-config')
require('telescope-config')
require('format-config')
require('blankline-config')
require('colorizer-config')
require('nvim-comment')
require('lsp')
vim.cmd('colorscheme nord')
